//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_MAS_AYAH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int Id { get; set; }
        public string First_Last_Day { get; set; }
        public string Subtype { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Condition { get; set; }
        public Nullable<int> usr_id { get; set; }
    
        public virtual Service_owners Service_owners { get; set; }
    }
}
